### PR TITLE
Move to GH Actions

### PR DESCRIPTION
**Pull request by CAMOBAP**
- https://github.com/metanorma/metanorma-build-scripts/issues/23

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 the YAML files for GitHub actions are invalid...

**Comment by ronaldtse** [comment]
@CAMOBAP795 please remember to enable the Ruby matrix 2.5 and 2.4, thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse we didn't do this before but np, I will add it

**Comment by ronaldtse** [comment]
Thanks. We do want our templates to be stable!

**Comment by ronaldtse** [comment]
@CAMOBAP795 we should use the metanorma (ubuntu.sh) install script?

**Comment by CAMOBAP** [comment]
@ronaldtse, in theory, yes, but in practice it will dramatically increase CI time

**Comment by ronaldtse** [comment]
Windows build still failing.

**Comment by CAMOBAP** [comment]
I have no idea why it happens works without any issues on my VirtualBox, temporally switching to https://github.com/metanorma/metanorma-linux-setup/commit/f234fa1be6a7b1dbb34d7802561834bc1ccfc900/checks?check_suite_id=364146654

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP795 !

**Pull request merged**
