### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by CAMOBAP**
- #4

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 for the spec commands, you need to use some option or code to test the actual template (such as the `-g` option in CLI). Right now it is testing the metanorma CLI with the master branch of the remote templates.

@abunashir can you help here by making the CLI allow testing of local templates?

**Comment by CAMOBAP** [comment]
> such as the -g option in CLI

@ronaldtse so test command should be like this `metanorma new test -d advisory -t csd -g https://github.com/metanorma/mn-templates-csd` ?

**Comment by ronaldtse** [comment]
Instead of:

```
metanorma new test -d advisory -t csd -g https://github.com/metanorma/mn-templates-csd 
```

It should probably be:
```
metanorma new test -d advisory -t csd -g ./
```

and

```
metanorma new test -d advisory -t csd -g https://github.com/metanorma/mn-templates-csd (but with branch set to $TRAVIS_BRANCH
```

Because we want to test to test the templates at the PR, not at master.

**Comment by ronaldtse** [comment]
You may have to change metanorma-cli for that.

**Comment by CAMOBAP** [comment]
@ronaldtse thanks for the explanation it's clear for me now, I will check if it works or implement this

**Comment by CAMOBAP** [comment]
@ronaldtse ready for review

**Comment by ronaldtse** [comment]
@CAMOBAP795 this is excellent 👍  Can you also apply this to the rest of the template repositories? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse for sure

**Pull request merged**
